### ISSUE TITLE
AppServiceMSICredentials does not work

### ISSUE THREAD

**Issue by justinpa-asg** [Azure/autorest-clientruntime-for-java#433]
I get:
```
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at com.microsoft.azure.credentials.AppServiceMSICredentials.getToken(AppServiceMSICredentials.java:71)
```

Unless I replace api-version=2017-09-01 with api-version=2018-02-01 and comment out:
```
//connection.setRequestProperty("Secret", this.secret);
```

I'm using endpoint http://169.254.169.254/metadata/identity/oauth2/token.

**Comment by mattchenderson** [comment]
@justinpa-asg Can you provide some more detail here? This endpoint looks like a request from Azure Virtual Machines, not App Service.

Are you following the [App Service documentation](https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity)?

**Comment by justinpa-asg** [comment]
@mattchenderson The following is in AppServiceMSICredentials:
```
    public String getToken(String resource) throws IOException {
        String urlString = String.format("%s?resource=%s&api-version=2017-09-01", this.endpoint, resource);
        ...
        connection.setRequestProperty("Secret", this.secret);
```
When I replace with:
```
    public String getToken(String resource) throws IOException {
        String urlString = String.format("%s?resource=%s&api-version=2018-02-01", this.endpoint, resource);
        ...
        //connection.setRequestProperty("Secret", this.secret);
```
And add the .class to my container's CLASSPATH, I am then able to use system identity within my application without observing the SocketException. I have found no test cases. Is anyone successfully using this feature? Any reason not to update api-version? Yes, I followed App Service documentation but I can see that it has changed over time.
