### ISSUE TITLE
Logging interceptor exhausts response content on PUT

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest-clientruntime-for-java#460]
I'm not able to get a clean repro of this one but when I run `ResourceGroups.create()` with log level set to BODY I get this error:
```
[main] INFO com.microsoft.azure.v2.management.resources.implementation.ResourceGroupsInner$ResourceGroupsService.createOrUpdate - --> PUT https://management.azure.com/subscriptions/ffa52f27-be12-4cad-b1ea-c2c241b6cceb/resourcegroups/rg630103?api-version=2016-09-01
[main] INFO com.microsoft.azure.v2.management.resources.implementation.ResourceGroupsInner$ResourceGroupsService.createOrUpdate - 82-byte body:
{
  "location" : "southcentralus",
  "tags" : {
    "tagname" : "tagvalue",
    "department" : "finance"
  }
}
[main] INFO com.microsoft.azure.v2.management.resources.implementation.ResourceGroupsInner$ResourceGroupsService.createOrUpdate - --> END PUT
[nioEventLoopGroup-1-2] INFO com.microsoft.azure.v2.management.resources.implementation.ResourceGroupsInner$ResourceGroupsService.createOrUpdate - <-- HTTP FAILED: java.lang.IllegalArgumentException: Flowable<ByteBuffer> emitted 0 bytes instead of the expected 82 bytes.
==> Playback file path: /Users/jianghlu/Documents/code/azure-libraries-for-java/azure-mgmt-resources/target/test-classes/session-records/canCreateResourceGroup.json

java.lang.IllegalArgumentException: Flowable<ByteBuffer> emitted 0 bytes instead of the expected 82 bytes.

	at com.microsoft.rest.v2.util.FlowableUtil$1.lambda$call$1(FlowableUtil.java:97)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:128)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:135)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:57)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener$RequestSubscriber.onSubscribe(NettyClient.java:352)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onSubscribe(BasicFuseableSubscriber.java:67)
	at io.reactivex.internal.operators.flowable.FlowableScalarXMap$ScalarXMapFlowable.subscribeActual(FlowableScalarXMap.java:158)
	at io.reactivex.Flowable.subscribe(Flowable.java:14291)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14291)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
	at io.reactivex.Flowable.subscribe(Flowable.java:14291)
	at io.reactivex.Flowable.subscribe(Flowable.java:14237)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:41)
	at io.reactivex.Flowable.subscribe(Flowable.java:14291)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete(NettyClient.java:309)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

If I set the log level to BASIC it runs fine. Doesn't repro for GET or POST operations.

**Comment by RikkiGibson** [comment]
Maybe we're failing to .buffer() the HttpResponse under certain conditions?

**Comment by jianghaolu** [comment]
@RikkiGibson  It seems like we buffer it here: https://github.com/Azure/autorest-clientruntime-for-java/blob/v2/client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLoggingPolicyFactory.java#L180.

**Comment by jianghaolu** [comment]
It actually fails even if I comment outhttps://github.com/Azure/autorest-clientruntime-for-java/blob/v2/client-runtime/src/main/java/com/microsoft/rest/v2/policy/HttpLoggingPolicyFactory.java#L176-L189
