### ISSUE TITLE
Runtime polls on method which is not marked as LRO

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest-clientruntime-for-java#466]
Invoking [this method](https://github.com/Azure/azure-libraries-for-java/blob/24e71137aef0f787809850859475cafbaf4a6798/azure-mgmt-trafficmanager/src/main/java/com/microsoft/azure/v2/management/trafficmanager/implementation/ProfilesInner.java#L94) cause the error 

`
com.microsoft.azure.v2.CloudException: The polling response does not contain a valid body
` 

The method is not a LRO in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/c169cfdac6ffcb5441db5fb39975fc177339b6cf/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2017-05-01/trafficmanager.json#L484) but runtime treat it as LRO and apply provisioning state based strategy.

To repro 

1. Get [this branch](https://github.com/anuchandy/azure-libraries-for-java/tree/v2-traffic-manager)
2. Run [this test](https://github.com/anuchandy/azure-libraries-for-java/blob/24e71137aef0f787809850859475cafbaf4a6798/azure-mgmt-trafficmanager/src/test/java/com/microsoft/azure/management/TrafficManagerTests.java#L63)

The stack trace is

```

[nioEventLoopGroup-1-1] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - --> PUT https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/tmergtest34973/providers/Microsoft.Network/trafficmanagerprofiles/tmprfb8376528?api-version=2017-05-01
[nioEventLoopGroup-1-2] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - <-- 201 Created https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/tmergtest34973/providers/Microsoft.Network/trafficmanagerprofiles/tmprfb8376528?api-version=2017-05-01 (2083 ms, 627-byte body)
[nioEventLoopGroup-1-2] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - <-- END HTTP
[RxComputationThreadPool-1] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - --> GET https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/tmergtest34973/providers/Microsoft.Network/trafficmanagerprofiles/tmprfb8376528?api-version=2017-05-01
[nioEventLoopGroup-1-1] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - <-- 200 OK https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/tmergtest34973/providers/Microsoft.Network/trafficmanagerprofiles/tmprfb8376528?api-version=2017-05-01 (470 ms, 627-byte body)
[nioEventLoopGroup-1-1] INFO com.microsoft.azure.v2.management.trafficmanager.implementation.ProfilesInner$ProfilesService.createOrUpdate - <-- END HTTP

com.microsoft.azure.v2.CloudException: The polling response does not contain a valid body

	at com.microsoft.azure.v2.ProvisioningStatePollStrategy$1$1.apply(ProvisioningStatePollStrategy.java:90)
	at com.microsoft.azure.v2.ProvisioningStatePollStrategy$1$1.apply(ProvisioningStatePollStrategy.java:80)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:59)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onSuccess(SingleTimeout.java:133)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:59)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleCache.onSuccess(SingleCache.java:134)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableCollectSingle$CollectSubscriber.onComplete(FlowableCollectSingle.java:119)
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.emitContent(NettyClient.java:883)
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.drain(NettyClient.java:843)
	at com.microsoft.rest.v2.http.NettyClient$ResponseContentFlowable.onReceivedContent(NettyClient.java:766)
	at com.microsoft.rest.v2.http.NettyClient$HttpClientInboundHandler.channelRead(NettyClient.java:991)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RikkiGibson** [comment]
I have a vague recollection we do something like check the operation metadata and the response to see if it looks like an LRO, and one of our LRO strategies happens to be a "no-op" strategy.

**Comment by jianghaolu** [comment]
Seems to have been fixed.
