### ISSUE TITLE
NPE in AdditionalPropertiesDeserializer while using jococo for test coverage

### ISSUE THREAD

**Issue by ashbondu** [Azure/autorest-clientruntime-for-java#536]
Seeing the following exception when the classes are instrumented using jococo.

java.lang.NullPointerException
        at com.microsoft.rest.serializer.AdditionalPropertiesDeserializer.deserialize(AdditionalPropertiesDeserializer.java:101)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:193)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.deserializeWithType(StdDeserializer.java:136)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:288)
 [wrapped] com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.microsoft.azure.management.graphrbac.implementation.PageImpl["value"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)

Jococo adds a $jococoData field to the instrumented classes, as a result it causes NPE in AdditionalPropertiesDeserializer when it checks for JsonProperty Annotation value.

Reference : https://github.com/jacoco/jacoco/issues/168

**Comment by akshitjain** [comment]
@ashbondu it is fixed? Are you still facing this issue?

**Comment by TilmanGieseSAP** [comment]
The issue still exists. I suppose a simple null check in `AdditionalPropertiesDeserializer.deserialize` would probably do the trick.
