### ISSUE TITLE
Running azure-storage-java code sample warns of illegal restricted access operation

### ISSUE THREAD

**Issue by mattvryan** [Azure/autorest-clientruntime-for-java#569]
I'm using [Azure Storage SDK for Java](https://github.com/Azure/azure-storage-java) and trying out the code examples.  I tried a very simple example based as closely as I could on the code sample in [their README.md](https://github.com/Azure/azure-storage-java/blob/master/README.md#code-sample). When I run my code, it creates the container, uploads the blob, verifies it, and then deletes the blob and container as expected. But warning messages are printed to the console about an illegal restricted access operation in the SDK code:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.microsoft.rest.v2.Validator to field java.util.HashMap.serialVersionUID
> WARNING: Please consider reporting this to the maintainers of com.microsoft.rest.v2.Validator
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

I'm reluctant to rely on this SDK in production with this warning present; are there plans to address this?

**Comment by mattvryan** [comment]
This was originally submitted to the Azure Storage SDK for Java project via [this issue](https://github.com/Azure/azure-storage-java/issues/447); at their request I've refiled it here.

**Comment by lgaudez** [comment]
Any plans to address this ? 

  ```
  SharedKeyCredentials credentials = new SharedKeyCredentials(accountName, accountKey);
  HttpPipeline pipeline = StorageURL.createPipeline(credentials); // Execute this line pops the warnings
```

**Comment by Bruno-Brant** [comment]
I'm having the same issue, using the downstream package mentioned above (azure-storage-blob, v10.5.0). I traced the issue down to a line on the file Validator.java (here shows up on line 112)

    field.setAccessible(true);

This causes the warning. I'm not that well-versed in Java, but I believe that the reason this is happening is that (for some reason) the JVM is not allowing a third-party package to change class member access (nor I think that should be the way of going about it, if you care about it 😊).

I don't know exactly what is the end result of this WARNING (the code seems to work), but this kind of warning in production might cause problems (even if of a more ...political... nature).

**Comment by lawrencegripper** [comment]
I'm also seeing this error, any movement on a fix?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.microsoft.rest.v2.Validator (file:/home/lawrence/source/hacks/-/pipeline/scoring/pipeline-scoring/target/pipeline-scoring-1.0-SNAPSHOT-jar-with-dependencies.jar) to field java.util.HashMap.serialVersionUID
WARNING: Please consider reporting this to the maintainers of com.microsoft.rest.v2.Validator
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jul 22, 2019 12:46:49 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete()
java.lang.NullPointerException
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.emitError(NettyClient.java:426)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete(NettyClient.java:247)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:322)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by frensjan** [comment]
I'd like to bump this issue a little: this will get problematic for a lot of users from Java 16 and up because the default for `--illegal-access` is changed to `deny` (see also https://www.oracle.com/java/technologies/javase/16-relnotes.html).

**Comment by weidongxu-microsoft** [comment]
Does this solved by https://github.com/Azure/autorest-clientruntime-for-java/commit/3f0105b24ed5c80e00628f2f641c2148a28b7f11?

**Comment by frensjan** [comment]
I don't think so. `field.setAccessible` is still called in `validateClass`.
